export const SET_USERS = 'SET_USERS';
export const START_USERS_LOADING = 'START_USERS_LOADING';
export const STOP_USERS_LOADING = 'STOP_USERS_LOADING';
export const SET_USERS_ERROR = 'SET_USERS_ERROR';
